
# Docker Compose file for SDMC LAMP stack and website

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    user: "0:0"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sdmc}
      MYSQL_USER: ${MYSQL_USER:-drupal}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_drupal_password
      SDMC_ENV: ${SDMC_ENV:-dev}
    volumes:
      - ${MYSQL_DATA_DIR:-./data/mysql}:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    secrets:
      - mysql_root_password
      - mysql_drupal_password
    networks: [back]

  php81-apache:
    build:
      context: ./php81-apache
      args:
        REQUIRED_PHP: "8.1"
        APACHE_SERVER_NAME: ${APACHE_SERVER_NAME:-dev.loc}
        APACHE_SERVER_ALIAS: ${APACHE_SERVER_ALIAS:-dev.loc}
        APACHE_DOCROOT: ${APACHE_DOCROOT:-/var/www/miraweb2024/docroot}
        SDMC_ENV: ${SDMC_ENV:-dev}
        SSL_CERT_FILE: ${SSL_CERT_FILE:-/certs/dev.crt}
        SSL_CERT_KEY_FILE: ${SSL_CERT_KEY_FILE:-/certs/dev.key}
    environment:
      SDMC_ENV: ${SDMC_ENV:-dev}      # still exported so PassEnv can expose it to PHP
    volumes:
      - ${DRUPAL_HOST_PATH}:/var/www/miraweb2024:delegated
      - ./php81-apache/vhosts/dev.conf.template:/etc/apache2/sites-available/dev.conf:ro
      - ./php81-apache/vhosts/dev-ssl.conf.template:/etc/apache2/sites-available/dev-ssl.conf:ro
      - ./php81-apache/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./certs:/certs:ro
    ports:
      - "${APACHE_PORT:-8081}:80"
      - "${APACHE_SSL_PORT:-8444}:443"
    depends_on: [mysql, memcached]
    networks: [front, back]

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    command: ["-m", "128", "-I", "2m"]
    ports:
      - "${MEMCACHED_PORT:-11211}:11211"
    networks: [back]

  node:
    build: ./node
    container_name: node
    working_dir: /workspace
    volumes:
      - ${DRUPAL_HOST_PATH}:/workspace:delegated
    command: ["tail", "-f", "/dev/null"]
    networks: [front, back]

  solr:
    image: solr:8.6.2
    container_name: solr
    environment:
      SOLR_JAVA_MEM: "-Xms512m -Xmx512m"
    volumes:
      - solr-data:/var/solr                  
      - ./solr-config/sdmc:/solr-config:ro 
    command: ["solr-precreate", "sdmc", "/solr-config"]
    ports:
      - "${SOLR_PORT:-8983}:8983"
    networks: [back]
    healthcheck:
      test: ["CMD", "bash", "-lc", "wget -qO- 'http://localhost:8983/solr/sdmc/admin/ping?wt=json' | grep -q '\"status\":\"OK\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
  composer:
    profiles: ["devtools"]
    image: php81-apache:latest
    pull_policy: never
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    working_dir: /app
    entrypoint: ["composer"]
    environment:
      COMPOSER_HOME: /tmp
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    volumes:
      - ${DRUPAL_HOST_PATH}:/app:rw
      - ./data/composer-cache:/tmp/composer-cache
    depends_on: [php81-apache]
networks:
  front:
  back:
volumes:
  solr-data:
secrets:
  mysql_root_password:
    file: ${MYSQL_ROOT_PASSWORD_FILE_HOST}
  mysql_drupal_password:
    file: ${MYSQL_DRUPAL_PASSWORD_FILE_HOST}

