CREATE DATABASE IF NOT EXISTS `drupal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'drupal'@'%' IDENTIFIED BY 'N0t@g00dP@ssw0rd!';
GRANT ALL PRIVILEGES ON `drupal`.* TO 'drupal'@'%';
FLUSH PRIVILEGES;

